
export const translations = {
    fr: {
        logo: "CMC <span class='text-blue-400'>Laâyoune</span>",
        nav_home: "Accueil",
        nav_about: "À Propos",
        nav_majors: "Filières",
        nav_infra: "Campus",
        nav_contact: "Contact",
        apply_btn: "Postuler",
        hero_badge: "Inscriptions Ouvertes 2024 - 2025",
        hero_title: "Forger les Leaders de <br><span class='text-blue-400'>Demain à Laâyoune</span>",
        hero_desc: "Le CMC Laâyoune est un pôle d'excellence dédié au Management et au Commerce. Préparez votre avenir avec une formation pratique.",
        hero_cta_1: "Nos Filières",
        hero_cta_2: "Contact",
        about_subtitle: "À propos de nous",
        about_title: "L'Excellence au Cœur de Laâyoune",
        about_text: "Le CMC Laâyoune est un pôle d'innovation dédié à la formation professionnelle supérieure. Nous préparons nos étudiants à devenir les leaders économiques de demain.",
        majors_subtitle: "Nos Filières",
        majors_title: "Spécialisations Professionnelles",
        majors_desc: "Des programmes adaptés aux besoins du marché.",
        infra_subtitle: "Infrastructures",
        infra_title: "Un Campus Moderne",
        life_subtitle: "Vie Étudiante",
        life_title: "Un Épanouissement Complet",
        gallery_subtitle: "Galerie",
        gallery_title: "Le Campus en Images",
        contact_info_title: "Informations",
        contact_addr: "Zone Industrielle, Laâyoune, Maroc",
        contact_form_title: "Laissez-nous un message",
        contact_send: "Envoyer le Message",
        placeholder_name: "Nom Complet",
        placeholder_email: "Email",
        placeholder_msg: "Votre message...",
        majors: [
            { name: "Gestion des Entreprises", desc: "Maîtrisez les fondamentaux du management moderne." },
            { name: "Commerce Digital", desc: "Devenez expert en stratégies de vente en ligne." },
            { name: "Systèmes d'Information", desc: "Concevez les architectures IT du futur." },
            { name: "Logistique & Transport", desc: "Optimisez les flux de marchandises mondiaux." }
        ],
        infra: [
            { title: "Amphithéâtre", desc: "Technologie 4K et acoustique parfaite." },
            { title: "Bibliothèque", desc: "Ressources numériques et physiques." },
            { title: "Labs IT", desc: "Stations de travail haute performance." },
            { title: "Cafétéria", desc: "Espace de détente moderne." }
        ],
        life: [
            { title: "Clubs", desc: "Art, Sport, et Tech." },
            { title: "Events", desc: "Conférences et Workshops." },
            { title: "Stages", desc: "Partenariats entreprises." },
            { title: "Coaching", desc: "Accompagnement carrière." }
        ]
    },
    ar: {
        logo: "مركز الإدارة والتجارة <span class='text-blue-400'>العيون</span>",
        nav_home: "الرئيسية",
        nav_about: "من نحن",
        nav_majors: "التخصصات",
        nav_infra: "الحرم الجامعي",
        nav_contact: "اتصل بنا",
        apply_btn: "قدم طلبك",
        hero_badge: "باب التسجيل مفتوح 2024 - 2025",
        hero_title: "صناعة قادة <br><span class='text-blue-400'>الغد بالعيون</span>",
        hero_desc: "مركز الإدارة والتجارة بالعيون هو قطب للتميز مخصص للإدارة والتجارة. استعد لمستقبلك بتكوين تطبيقي حديث.",
        hero_cta_1: "تخصصاتنا",
        hero_cta_2: "اتصل بنا",
        about_subtitle: "نبذة عنا",
        about_title: "التميز في قلب العيون",
        about_text: "مركز الإدارة والتجارة بالعيون هو قطب ابتكار مخصص للتكوين المهني العالي. نعد طلابنا ليكونوا قادة الاقتصاد في الغد.",
        majors_subtitle: "تخصصاتنا",
        majors_title: "تخصصات مهنية",
        majors_desc: "برامج تتكيف مع احتياجات السوق المحلية والدولية.",
        infra_subtitle: "البنية التحتية",
        infra_title: "حرم جامعي عصري",
        life_subtitle: "الحياة الطلابية",
        life_title: "تطور شخصي متكامل",
        gallery_subtitle: "المعرض",
        gallery_title: "الحرم الجامعي بالصور",
        contact_info_title: "معلومات الاتصال",
        contact_addr: "الحي الصناعي، العيون، المغرب",
        contact_form_title: "اترك لنا رسالة",
        contact_send: "إرسال الرسالة",
        placeholder_name: "الاسم الكامل",
        placeholder_email: "البريد الإلكتروني",
        placeholder_msg: "رسالتك...",
        majors: [
            { name: "تسيير المقاولات", desc: "إتقان أساسيات الإدارة الحديثة." },
            { name: "التجارة الرقمية", desc: "كن خبيراً في استراتيجيات البيع عبر الإنترنت." },
            { name: "نظم المعلومات", desc: "تصميم بنيات تكنولوجيا المعلومات للمستقبل." },
            { name: "اللوجستيك والنقل", desc: "تحسين تدفق البضائع العالمي." }
        ],
        infra: [
            { title: "مدرج المحاضرات", desc: "تكنولوجيا 4K وصوتيات مثالية." },
            { title: "المكتبة", desc: "موارد رقمية وورقية متنوعة." },
            { title: "مختبرات تقنية", desc: "محطات عمل عالية الأداء." },
            { title: "المقصف", desc: "فضاء عصري للاسترخاء." }
        ],
        life: [
            { title: "الأندية", desc: "فن، رياضة وتكنولوجيا." },
            { title: "الفعاليات", desc: "ندوات وورش عمل." },
            { title: "التدريبات", desc: "شراكات مع المقاولات." },
            { title: "التوجيه", desc: "مواكبة مهنية مستمرة." }
        ]
    },
    en: {
        logo: "CMC <span class='text-blue-400'>Laayoune</span>",
        nav_home: "Home",
        nav_about: "About",
        nav_majors: "Majors",
        nav_infra: "Campus",
        nav_contact: "Contact",
        apply_btn: "Apply",
        hero_badge: "Admissions Open 2024 - 2025",
        hero_title: "Shaping Tomorrow's <br><span class='text-blue-400'>Leaders in Laayoune</span>",
        hero_desc: "CMC Laayoune is an excellence hub dedicated to Management and Commerce. Prepare your future with professional training.",
        hero_cta_1: "Our Majors",
        hero_cta_2: "Contact Us",
        about_subtitle: "About Us",
        about_title: "Excellence in the Heart of Laayoune",
        about_text: "CMC Laayoune is an innovation hub dedicated to higher vocational training. We prepare students to become tomorrow's economic leaders.",
        majors_subtitle: "Our Majors",
        majors_title: "Professional Specializations",
        majors_desc: "Programs adapted to market needs.",
        infra_subtitle: "Infrastructure",
        infra_title: "A Modern Campus",
        life_subtitle: "Student Life",
        life_title: "Complete Fulfillment",
        gallery_subtitle: "Gallery",
        gallery_title: "Campus in Images",
        contact_info_title: "Contact Info",
        contact_addr: "Industrial Zone, Laayoune, Morocco",
        contact_form_title: "Leave us a message",
        contact_send: "Send Message",
        placeholder_name: "Full Name",
        placeholder_email: "Email",
        placeholder_msg: "Your message...",
        majors: [
            { name: "Business Management", desc: "Master the fundamentals of modern management." },
            { name: "Digital Commerce", desc: "Become an expert in online sales strategies." },
            { name: "Information Systems", desc: "Design future IT architectures." },
            { name: "Logistics & Transport", desc: "Optimize global goods flows." }
        ],
        infra: [
            { title: "Amphitheater", desc: "4K technology and perfect acoustics." },
            { title: "Library", desc: "Digital and physical resources." },
            { title: "IT Labs", desc: "High performance workstations." },
            { title: "Cafeteria", desc: "Modern relaxation space." }
        ],
        life: [
            { title: "Clubs", desc: "Art, Sport, and Tech." },
            { title: "Events", desc: "Conferences and Workshops." },
            { title: "Internships", desc: "Corporate partnerships." },
            { title: "Coaching", desc: "Career guidance support." }
        ]
    }
};
